config/routes.rb
Houndalytics::Application.routes.draw do

  

  resource :login
  
  resources :customers do
    resources :events
  end

  get "sign_in" => "logins#new", as: "log_in"
  root to: "logins#new"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :sites, dependent: :destroy
	has_many :events, through: :sites
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :site
end

app/models/site.rb
class Site < ActiveRecord::Base

  belongs_to :customer
  has_many :events

end

app/models/site_finder.rb
require 'uri'

# Either find a site based on hostname, or create one when none can be found.
class SiteFinder

	def initialize(event_params, referer, customer)
		@event_params = event_params
		@referer = referer
		@customer = customer
	end

	def create

		@site = @customer.sites.find_or_create_by(hostname: hostname)
		
		#if @customer.sites.where(hostname: hostname).empty? # [] [<Site>, ..]
			#@site = @customer.sites.create hostname: hostname
		#else
			#@site = @customer.sites.where(hostname: hostname).first
		#end

		@event = @site.events.create
	end

	private
	def hostname
		# parse @referer header and strip out hostname
		uri = URI(@referer)
		uri.host
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	def current_user

	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def new
		@customer = Customer.new
	end

	def create
		@customer = Customer.new(customer_params)
		if @customer.save
			redirect_to @customer, notice: "customer created successfully"
		else
			flash[:error] = "Error creating customer, please try again"
			render :new
		end
	end

	def index
		@customers = Customer.all
		if current_user
			render :index
		else
			redirect_to root_url, notice: "ACCESS DENIED!!!111ONE"
		end
	end

	private
	def  customer_params
		params.require(:customer).permit(:name)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :find_customer

	def index
		@events = @customer.events
		# @event = @customer.events.find(params[:event_id])

		if params[:start_date] && params[:end_date]
			@events = @customer.events.where("date(events.created_at) >= ? AND date(events.created_at) <= ?", params[:start_date], params[:end_date] )
		end
	end

	def create
		SiteFinder.new(params[:event], request.referer, @customer).create

		render json: {status: "OK"}
	end

	private

	def find_customer
		@customer = Customer.find(params[:customer_id])
	end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

	def new
	end

	def create
		# check valid pw
		# fields will be: params[:email] and params[:password]
		user = User.find_by(email: params[:email]).try(:authenticate, params[:password])

		if user
			session[:user_id] = user.id
			redirect_to customers_path
		else
			flash[:error] = "Username not recognised"
			render 'new'
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_url, notice: "Signed Up!"
		else
			render "new"
		end
	end

	private
	def  user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/_customer.html.erb
<%= customer.name %>

app/views/customers/_customer.html.slim
li.list-group-item
   == customer.name
   span.badge 14

app/views/customers/index.html.erb
<%= render @customers %>

app/views/customers/index.html.slim
ul.list-group
  == render @customers

app/views/events/_event.html.slim
li
  = event.url

app/views/events/index.html.slim
= form_tag customer_events_path(@customer), method: :get do
  
  = label_tag :start_date, "Start date"	
  = date_field_tag :start_date

  = label_tag :end_date, "End date"
  = date_field_tag :end_date

  = submit_tag "Show date range"

ul
  = render @events
  / = render partial: "event", collection: @events

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Houndalytics</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title Houndalytics
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  
  body

  	- flash.each do | name, msg |
      div class=name
        p = msg


	== yield

app/views/logins/new.html.erb
<h1>Log in</h1>

<p>Please log in to Houndalytics.</p>

<%= form_tag login_path do %>

	<%= email_field_tag :email %>
	<%= password_field_tag :password %>

	<%= submit_tag "Log in" %>

<% end %>

app/views/logins/new.html.slim
h1 login

p Please log in to Houndalytics.

= form_tag login_path do

  = email_field_tag :email
  = password_field_tag :password

  = submit_tag "Log in"